---
abstract: 'GraphViz output for PYX handling.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PYX-GraphViz
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.05
  Error::Pure: 0.15
  GraphViz: 0
  PYX::Parser: 0.02
  perl: 5.6.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/PYX-GraphViz/issues
  homepage: https://github.com/michal-josef-spacek/PYX-GraphViz
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/PYX-GraphViz
version: '0.05'
